// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhhCiKdIRoUgr8BxeIofympCPxPkahtQw',
    appId: '1:497710478676:web:f63ff9084e64729d3bc4c1',
    messagingSenderId: '497710478676',
    projectId: 'digitalacademy-69c3d',
    authDomain: 'digitalacademy-69c3d.firebaseapp.com',
    storageBucket: 'digitalacademy-69c3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWofppqe0KuaG0qifsGCRgVSrCIMtV_o',
    appId: '1:497710478676:android:6c6b7e365c54c0333bc4c1',
    messagingSenderId: '497710478676',
    projectId: 'digitalacademy-69c3d',
    storageBucket: 'digitalacademy-69c3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq8qaZutxxC4G3_ucuAiq_I909gX690vE',
    appId: '1:497710478676:ios:9994ac80dd08ba2a3bc4c1',
    messagingSenderId: '497710478676',
    projectId: 'digitalacademy-69c3d',
    storageBucket: 'digitalacademy-69c3d.appspot.com',
    iosBundleId: 'com.example.digitalAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq8qaZutxxC4G3_ucuAiq_I909gX690vE',
    appId: '1:497710478676:ios:9994ac80dd08ba2a3bc4c1',
    messagingSenderId: '497710478676',
    projectId: 'digitalacademy-69c3d',
    storageBucket: 'digitalacademy-69c3d.appspot.com',
    iosBundleId: 'com.example.digitalAcademy',
  );
}
